### ISSUE TITLE
composer install --no-interaction

### ISSUE THREAD

**Issue by cepheiVV** [cepheiVV/setup-typo3-dev-env#7]
composer install prompts
> Do you trust "typo3/cms-composer-installers" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y

Can we run `composer install --no-interaction` to accept all? without further prompts during the install process?

<img width="706" alt="Screenshot 2022-06-18 at 13 23 34" src="https://user-images.githubusercontent.com/2963482/174425741-af3e8124-7457-4756-804b-022631e1dc41.png">

**Comment by janslu** [comment]
@cepheiVV I have added a logic to make changes to site package composer.json and ext_emconf.php if mask extension is installed. This is something I wasn't aware of, but took me 2 hours yesterday. Without setting mask as a dependency of a site package it may be impossible for example add crop variants to file referenced images (this was my case)...

**Comment by janslu** [comment]
And one more note - adding  `--no-interaction` is enough, but adding `allow-plugins` section suppresses warnings and probably is a good idea in the long run anyway...

**Comment by cepheiVV** [comment]
thank you!
